Changes to Sorcha logging, utility script
dirac-institute/sorcha pull request #1012
Opened 2024-09-03 16:28 UTC by astronomerritt

Fixes #1003.
- All log files now share an output prefix with the Sorcha output file they are associated with, to aid location of bad runs.
- Wrote a utility script that will recursively search for all Sorcha log files in a given directory/subdirectories and check to see whether the Sorcha runs were successfully completed. Usage given below.
- Unit tests.

Usage for the new utility script is as follows. I put it in the outputs section of the command line utilities, as that made the most sense.

```
>> sorcha outputs check-logs <top level directory filepath> <optional output filepath>
```

The output file is a .csv consisting of the log filename, a True/False flag as to whether the run was successfully completed, and if not, the last line of the log file.

If you don't supply an output filename, it'll just output everything to the terminal. If all runs were successful, **no output file is created**, as I didn't see the point really. A happy message is printed to the terminal instead.

All unit tests pass on my machine.

## Review Checklist for Source Code Changes

- [x] Does pip install still work?
- [x] Have you written a unit test for any new functions?
- [x] Do all the units tests run successfully?
- [x] Does Sorcha run successfully on a test set of input files/databases?
- [x] Have you used black on the files you have updated to confirm python programming style guide enforcement?

2024-09-03 18:48 UTC, Gerenjie commented
Works on my side! I ran a few simulations (tens of thousands of objects) on the new branch, saw that my output files were now helpfully named and readable, and used `sorcha outputs check-logs -f .` to confirm that my runs worked!

2024-09-04 21:07 UTC, mschwamb requested changes
doesn't this need to be added to [pyproject.toml](https://github.com/dirac-institute/sorcha/blob/main/pyproject.toml)?

2024-09-05 08:34 UTC, astronomerritt commented
Nope! sorcha-outputs is already in pyproject.toml, and I added this command there.

2024-09-05 08:58 UTC, mschwamb approved these changes

2024-09-05 08:58 UTC, merged