some more rng changes
dirac-institute/sorcha pull request #581
Opened 2023-09-01 22:26 UTC by maxwest-uw

Fixes #563 , fixes #567 .

Removes the rng_seed read in in `PPConfigParser`, creates a new hidden-ish variable in `sorchaArguments` to keep track of the rng seed, and prints out the seed in `pplogger`.

Note that this slightly changes the API of manually setting the rng_seed. You can still set the rng generator to use a seed of your choosing but if you don't also change the `_rng_seed` variable it will print out the default seed based on time, i.e. not the one that's actually being used in the numpy rng. (we could add a method to handle both changes at once and "refresh" the rng with a new seed but adding that functionality seems to go against the purpose of hiding it in the first place, right?)

## Review Checklist for Source Code Changes

- [x] Does pip install still work?
- [x] Have you written a unit test for any new functions?
- [x] Do all the units tests run successfully?
- [x] Does Sorcha run successfully on a test set of input files/databases?
- [x] Have you used black on the files you have updated to confirm python programming style guide enforcement?

2023-09-01 22:29 UTC, mschwamb commented
#566 does some refactoring of the random seed. So this should wait until that goes in and that rebase. I am not sure there will be much needed to be updated here, but worth doing things in that order I think

2023-09-01 23:41 UTC, mschwamb commented
Looks like #582 needs to be merged first

2023-09-02 00:08 UTC, mschwamb requested changes
Conflicts need to be addressed first

2023-09-07 21:40 UTC, maxwest-uw commented
there were multiple reworks of how rng works after this pr was opened so I'm just going to close this and redo the changes since that's easier than merging 😅

2023-09-07 21:40 UTC, closed without merging