Changed the code around initialization of t_picket.
dirac-institute/sorcha pull request #667
Opened 2023-09-28 17:16 UTC by matthewholman

Fixes # 666

This eliminates the hard-coded initial value for t_picket and includes some comments regarding why an initial value is needed.

## Review Checklist for Source Code Changes

- [ ] Does pip install still work?
- [ ] Have you written a unit test for any new functions?
- [ ] Do all the units tests run successfully?
- [ ] Does Sorcha run successfully on a test set of input files/databases?
- [ ] Have you used black on the files you have updated to confirm python programming style guide enforcement?

2023-09-28 19:15 UTC, drewoldag approved these changes
This looks fine to me, but in order to get the unit tests to pass, I think that you'll need to remove the references to `gm_total`. I've added a couple of "suggested changes" so you should be able to click "add suggestion to batch" on both of them, then commit them in a single commit to get the unit tests passing.

2023-09-28 19:15 UTC, drewoldag commented on src/sorcha/ephemeris/simulation_driver.py
> +    ephem, gm_sun, gm_total = create_assist_ephemeris(args)
I think that this line, and the change on line 88 shouldn't be included in this PR. These are accidental inclusions from the other PR that is in progress now, correct?

2023-09-28 19:15 UTC, drewoldag commented on src/sorcha/ephemeris/simulation_driver.py
> +    ephem, gm_sun, gm_total = create_assist_ephemeris(args)
```suggestion
    ephem, gm_sun = create_assist_ephemeris(args)
```

2023-09-28 19:15 UTC, drewoldag commented on src/sorcha/ephemeris/simulation_driver.py
> +    sim_dict = generate_simulations(ephem, gm_sun, gm_total, orbits_df)
```suggestion
    sim_dict = generate_simulations(ephem, gm_sun, orbits_df)
```

2023-09-28 20:42 UTC, matthewholman reviewed
Thanks!

2023-09-28 20:55 UTC, drewoldag commented
Meg called out that 0 could potentially be a problem is some cases where observations in the 1970s are being considered. 

An alternative to using `t_picket = 0` would be to use the negative machine limit for integers like `t_picket = np.iinfo(np.int32)`. 

Using that approach the initial value for `t_picket = -2147483648`

2023-09-28 21:13 UTC, matthewholman commented
JD = 0 is January 1, 4713 BC.  I think we're ok.

2023-09-28 23:31 UTC, drewoldag requested changes
We need to add back in the `ephemeris_csv_filename = None` line.

2023-09-28 23:31 UTC, drewoldag commented on src/sorcha/ephemeris/simulation_driver.py
> -    ephemeris_csv_filename = None
I think removing this line is a problem. It will cause runtime errors if an output file isn't specified.

2023-09-28 23:46 UTC, drewoldag approved these changes
I added the `ephemeris_csv_filename = None` line back in, so we should be good to go.

2023-09-29 04:02 UTC, mschwamb commented
Ah it's JD. I thought it was in MJD. 0 is fine. I'm going to merge in.

2023-09-29 04:02 UTC, merged