Adding command to copy config files.
dirac-institute/sorcha pull request #780
Opened 2024-01-15 14:07 UTC by astronomerritt

Fixes #776 .

There is now a command (`sorcha_copy_configs`) which will, when run, copy the example configuration files from where-ever Sorcha is installed on the user's machine to a location of their choosing (or, by default, the current working directory). The user can also choose (via command-line flag) whether to copy the Rubin config files, the demo config file, or all of them. Usage:

`sorcha_copy_configs [-h] [-f FILEPATH] [-c [{rubin,demo,all}]]`

Updated pyproject.toml, also wrote a unit test.

## Review Checklist for Source Code Changes

- [x] Does pip install still work?
- [x] Have you written a unit test for any new functions?
- [x] Do all the units tests run successfully?
- [x] Does Sorcha run successfully on a test set of input files/databases?
- [x] Have you used black on the files you have updated to confirm python programming style guide enforcement?

2024-02-05 11:01 UTC, mschwamb commented
From the sorcha calls it was discussed that it would be good to make this interactive so the user can see the options and select which config file they want or if they want them all and then confirm their answer through the keyboard

2024-02-06 11:24 UTC, astronomerritt commented
Changes:

- The user now interacts with the command line to select which config files they want, instead of using command line flags, by following prompts printed to the terminal.
- Added a function that parses and error handles the user input.
- Wrote a unit test to cover the above function.

Let me know if I should add more explanatory text to the information printed to the terminal.

2024-02-06 12:55 UTC, mschwamb commented
Likely the user only wants 1 rubin config file. Let's give them the option to download each one

2024-02-06 12:56 UTC, mschwamb commented
where the config files get copied to can be a config variable

2024-02-06 14:32 UTC, astronomerritt commented
Changes made:

- The user now specifies the location to which the files are copied on the command line using the -f flag. The default is the current directory. This brings it in line with the cache script.
- The utility now allows the user to select either the Rubin circular approximation or the Rubin full footprint config file.

2024-02-06 14:39 UTC, mschwamb requested changes
raceback (most recent call last):
  File "/Users/mschwamb/mambaforge/envs/sorcha/bin/sorcha_copy_configs", line 8, in <module>
    sys.exit(main())
  File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha_main_repo/sorcha/src/sorcha/utilities/sorcha_copy_configs.py", line 112, in main
    parser.add_argument(
NameError: name 'parser' is not defined

2024-02-06 14:50 UTC, astronomerritt commented
Oops. Fixed.

2024-02-06 14:51 UTC, mschwamb commented
Let's take the demo config file. We are packaging the demo files. The user can grab the demo config file from that

2024-02-06 16:27 UTC, mschwamb commented
Which configuration file(s) would you like to copy?:

1. Rubin-specific configuration file using circular approximation of camera footprint (faster).

2. Rubin-specific configuration file using full camera footprint (slower, but more accurate).

3. All.

Please enter a number and hit Return/Enter.
4
Traceback (most recent call last):
  File "/Users/mschwamb/mambaforge/envs/sorcha/bin/sorcha_copy_configs", line 8, in <module>
    sys.exit(main())
  File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha_main_repo/sorcha/src/sorcha/utilities/sorcha_copy_configs.py", line 129, in main
    which_configs = parse_file_selection(file_select)
  File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha_main_repo/sorcha/src/sorcha/utilities/sorcha_copy_configs.py", line 83, in parse_file_selection
    which_configs = selection_dict[file_select]
KeyError: 4

2024-02-06 16:35 UTC, mschwamb commented
It will copy over a file if I already have it in the directory. Would be good to add a -f flag and force people to double check that they want us to overwrite on a file they already have.

2024-02-06 16:36 UTC, mschwamb commented
Maybe not a -f but something that says yeah overwrite what I currently have in the directory

2024-02-06 16:37 UTC, mschwamb commented
I'd follow what the download script is doing
  --cache CACHE  Local directory where downloaded files will be stored.
  -f, --force    Delete and re-download data files.

2024-02-06 16:46 UTC, astronomerritt commented
Makes sense. I may go for `--path PATH` and then `-f --force`, if that suits.

2024-02-06 16:53 UTC, mschwamb commented
Whatever works

2024-02-06 22:48 UTC, mschwamb approved these changes

2024-02-06 22:48 UTC, merged