Adding script to print demo command to terminal.
dirac-institute/sorcha pull request #822
Opened 2024-02-15 17:56 UTC by astronomerritt

Fixes #692 .

- There is now a demo command that spits out the command which runs Sorcha from the demo files. It can be run by running `sorcha_demo_command`.
- This command also tells the user how to run `sorcha_copy_demo_files` to get the demo files.
- I'm not sure there's much point in a unit test for this function, as it only outputs text to the terminal, but I wrote one anyway so CodeCov stays happy.
- Additionally, `sorcha_copy_demo_files` now also prints the demo command to the terminal.

## Review Checklist for Source Code Changes

- [x] Does pip install still work?
- [x] Have you written a unit test for any new functions?
- [x] Do all the units tests run successfully?
- [x] Does Sorcha run successfully on a test set of input files/databases?
- [x] Have you used black on the files you have updated to confirm python programming style guide enforcement?

2024-02-15 20:40 UTC, mschwamb commented on tests/sorcha/test_sorcha_demo_command.py
This only tests that the output from the function is correct. If the command line arguments were changed  this would not catch it. 
Can you use os.system() and check the error file is empty and there is output?

2024-02-15 20:48 UTC, mschwamb requested changes
I think there should be a function that returns back a string of just the demo command line to run. Then I think it would be possible to use os.system to see if it successfully runs.

2024-02-16 00:23 UTC, astronomerritt commented on tests/sorcha/test_sorcha_demo_command.py
Yep, I know - I haven't done the second part yet, I was getting this out of the way first.

2024-02-16 00:24 UTC, astronomerritt commented
Agreed. I'll get that done tomorrow and add it to this PR then.

2024-02-16 11:45 UTC, astronomerritt commented
I have no idea why CodeCov is showing such a dramatic dip in project coverage - if anything it should be increasing now that we're covering `main()` in sorcha.py.

2024-02-16 11:52 UTC, astronomerritt commented
Ah. CodeCov has stopped ignoring citation_text.py. I believe this is because I'm now running sorcha.py as part of a unit test, which imports `cite_sorcha` - CodeCov can ignore a file, but it's not ignoring the function if it's imported by something else. Not sure how to fix this just yet.

2024-02-17 14:33 UTC, mschwamb approved these changes

2024-02-17 14:34 UTC, merged